[package]
name = "y2016"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
aoc = { "path" = "../aoc" }
prelude = { "path" = "../prelude" }
utils = { "path" = "../utils" }
