#!/usr/bin/env python3

import importlib

from utils import import_challenge, read_input

def run_challenge(year, challenge_number):
    try:
        challenge = import_challenge(year, challenge_number)
    except ImportError as e:
        if "No module named" in str(e):
            print(f'No solution for challenge {challenge_number:02d}')
            return
        else:
            print(e)
            return

    print(f'== Advent of Code {year} Challenge {challenge_number}')

    print('= Part 1 =')
    print(challenge.part1(read_input(year, challenge_number)))
    print('= Part 2 =')
    print(challenge.part2(read_input(year, challenge_number)))
    print()

if __name__ == '__main__':
    challenges = range(1, 26)

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("year", nargs='?', type=str, default='2017')
    parser.add_argument("challenges", type=int, nargs='*', default=challenges)
    args = parser.parse_args()

    for c in args.challenges:
        if c not in challenges:
            print("Error: Challenge {} does not exist".format(c))
            continue

        run_challenge(args.year, c)
