[package]
name = "y2015"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
md5 = { workspace = true }

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }
