[package]
name = "y2015"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
serde_json = "1.0.87"

aoc = { "path" = "../aoc" }
prelude = { "path" = "../prelude" }
utils = { "path" = "../utils" }
