[package]
name = "y2015"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.10.0"
itertools = "0.10.5"
md5 = "0.7.0"
once_cell = "1.15.0"
serde_json = "1.0.87"

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }