[package]
name = "y2015"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
md5 = { workspace = true }
serde_json = { workspace = true }

aoc = { "path" = "../aoc" }
prelude = { "path" = "../prelude" }
utils = { "path" = "../utils" }
