#!/usr/bin/env python3

import importlib

def read_input(challenge_number):
    filename = "{}.input".format(challenge_number)

    with open(filename) as f:
        challenge_input = f.read()

    return challenge_input

def run_challenge(challenge_number):
    print()
    print("Advent of Code Challenge {}".format(challenge_number))
    print("---------------------------")

    challenge = __import__(str(challenge_number))

    challenge_input = read_input(challenge_number)
    challenge_input = challenge.transform_input(challenge_input)
    print("= Part 1 =")
    challenge.part1(challenge_input)
    print("= Part 2 =")
    challenge.part2(challenge_input)

if __name__ == '__main__':
    challenges = [1, 2]

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("challenges", type=int, nargs='*', default=challenges)
    args = parser.parse_args()

    for c in args.challenges:
        if c not in challenges:
            print("Error: Challenge {} does not exist".format(c))
            continue

        run_challenge(c)
