#!/usr/bin/env python3

import importlib

from utils import import_challenge, read_input

def run_challenge(challenge_number):
    try:
        challenge = import_challenge(challenge_number)
    except ImportError as e:
        if "No module named" in str(e):
            print("No solution for challenge {0:02d}".format(challenge_number))
            return
        else:
            print(e)
            return

    print("== Advent of Code Challenge {}".format(challenge_number))

    challenge_input = read_input(challenge_number)

    print("= Part 1 =")
    print(challenge.part1(challenge_input))
    print("= Part 2 =")
    print(challenge.part2(challenge_input))
    print()

if __name__ == '__main__':
    challenges = range(1, 26)

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("challenges", type=int, nargs='*', default=challenges)
    args = parser.parse_args()

    for c in args.challenges:
        if c not in challenges:
            print("Error: Challenge {} does not exist".format(c))
            continue

        run_challenge(c)
