[package]
name = "utils"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
fancy-regex = { workspace = true }
itertools = { workspace = true }
priority-queue = { workspace = true }
