[package]
name = "aoc"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
console = { workspace = true }
ctrlc = { workspace = true }
