[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
console = "0.14.1"
ctrlc = { version = "3.1.9", features = ["termination"] }
dialoguer = "0.8.0"
indicatif = "0.15.0"