help:
	@just --list

build:
	@cargo build --release

run-year YEAR:
	@cargo run --release -- {{YEAR}}

run YEAR DAY:
	@cargo run --release -- {{YEAR}} {{DAY}}

profile YEAR DAY:
	@mkdir -p ./target/flamegraphs
	@cargo flamegraph --flamechart --deterministic --root --open --output ./target/flamegraphs/{{YEAR}}-{{DAY}}-$(date +%s).svg -- {{YEAR}} {{DAY}}

new YEAR DAY:
	@cp --no-clobber template.rs ./src/y{{YEAR}}/src/d{{DAY}}.rs && sed -i 's/DAY/{{DAY}}/g' ./src/y{{YEAR}}/src/d{{DAY}}.rs && sed -i 's/type D{{DAY}} = Unsolved/type D{{DAY}} = d{{DAY}}::Day{{DAY}}/g' ./src/y{{YEAR}}/src/lib.rs && touch ./src/y{{YEAR}}/src/d{{DAY}}.in

progress:
	@cargo run --release
