[package]
name = "y2022"
version.workspace = true
edition.workspace = true

[dependencies]
aoc = { "path" = "../aoc" }
prelude = { "path" = "../prelude" }
serde_json = "1.0.89"
utils = { "path" = "../utils" }
