[package]
name = "y2022"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
serde_json = { workspace = true }

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }
