[package]
name = "prelude"
version.workspace = true
edition.workspace = true

[dependencies]
fancy-regex = "0.10.0"
itertools = "0.10.5"

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }
hashbrown = "0.13.1"
