[package]
name = "prelude"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
fancy-regex = { workspace = true }
hashbrown = { workspace = true }
itertools = { workspace = true }

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }
