[package]
name = "y2021"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }

aoc = { "path" = "../aoc" }
utils = { "path" = "../utils" }
